const providersConstant = {
    SAVE_USER: 'SAVE_USER',
    FOLLOWING_POSTS: 'FOLLOWING_POSTS',
    UPDATE_USER: "UPDATE_USER",
    REQUESTED_TO_FOLLOW_NOTIFICATION: "REQUESTED_TO_FOLLOW_NOTIFICATION",
    FOLLOW_REQUEST_ACCEPTED_NOTIFICATION: "FOLLOW_REQUEST_ACCEPTED_NOTIFICATION",
    CHANGE_NOTIFICATION_STATUS: 'CHANGE_NOTIFICATION_STATUS',
    FOLLOW_ACCEPTED: 'FOLLOW_ACCEPTED',
    NEW_POST: 'NEW_POST',
    LOGOUT: 'LOGOUT'
}
export default providersConstant;